# Generated by Django 5.2.7 on 2025-11-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ministry_announcement_donation_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced'), ('separated', 'Separated'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='suffix',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
