# Generated by Django 5.2.7 on 2025-11-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_memberprofile_first_name_memberprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
