# Generated by Django 5.2.7 on 2026-04-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_memberprofile_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='fund_type',
            field=models.CharField(choices=[('Donation', 'Donation'), ('Others', 'Others')], default='Donation', max_length=50),
        ),
        migrations.AddField(
            model_name='donation',
            name='gcash_reference',
            field=models.CharField(default='OLD-REF', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='method',
            field=models.CharField(default='GCash', max_length=10),
        ),
    ]
