# Generated by Django 5.2.7 on 2026-04-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_donation_fund_type_donation_gcash_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='gcash_reference',
        ),
        migrations.AlterField(
            model_name='donation',
            name='fund_type',
            field=models.CharField(choices=[('Donation', 'Donation'), ('Offering', 'Offering')], default='Donation', max_length=50),
        ),
    ]
