# Generated by Django 5.2.7 on 2026-04-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_donation_gcash_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='fund_type',
            field=models.CharField(choices=[('Donations', 'Donations')], default='Donations', max_length=50),
        ),
    ]
